update readme with code minimally
pyt-team/TopoModelX pull request #287
Opened 2024-10-20 20:35 UTC by USFCA-MSDS

update readme file with minimal code

2024-10-20 20:36 UTC, USFCA-MSDS commented
@ffl096 @devendragovil  do you know why the lint is failing here? I forked from main, and only updated the readme file. Can you please take a look ?

2024-10-20 21:29 UTC, USFCA-MSDS commented
@ffl096 , all tests pass, please take a look at the updated readme and the pyproject files and merge if you approve.

2024-10-21 07:07 UTC, ffl096 requested changes

2024-10-21 07:07 UTC, ffl096 commented on README.md
> +dataset = karate_club(complex_type="simplicial")
`karate_club` is not part of TopoModelX but TopoNetX.

```suggestion
import toponetx as tnx
from topomodelx.nn.simplicial.san import SAN
from topomodelx.utils.sparse import from_sparse

# Step 1: Load the Karate Club dataset
dataset = tnx.karate_club(complex_type="simplicial")
```

2024-10-21 07:07 UTC, ffl096 commented on pyproject.toml
> +issues = "https://github.com/pyt-team/TopoModelX/issues"
```suggestion
documentation = "https://pyt-team.github.io/TopoModelX"
source = "https://github.com/pyt-team/TopoModelX"
issues = "https://github.com/pyt-team/TopoModelX/issues"
```

2024-10-21 07:07 UTC, ffl096 commented on pyproject.toml
> +ignore = ["E501", "SIM115"] # line too long
Please revert.

2024-10-21 08:29 UTC, merged